### ISSUE TITLE
[Feature request]: Add function to save tree to file

### ISSUE THREAD

**Issue by Groz17** [AdiY00/copy-tree.nvim#1]
Would you consider adding a function for example called `save_tree` that expects a path to store the tree? This is because sometimes I don't want to pollute my clipboard register, but I still want to save the tree. Thanks!

**Comment by AdiY00** [comment]
For sure!
working on it.

**Comment by AdiY00** [comment]
Done.
Let me know what you think :)

**Comment by Groz17** [comment]
I've updated and used the function successfully, thank you very much 😃
