### ISSUE TITLE
Why `valid_extensions` over `invalid_extensions`?

### ISSUE THREAD

**Issue by kohane27** [AdiY00/copy-tree.nvim#2]
Hello there! Nice extension!

I was trying to use this plugin but then I found the file content are empty. Turned out that terraform file extension `.tf` is not in the `valid_extensions` table. But there are so many file extensions that using `valid_extensions` seems hard to maintain and inconvenient. Is there any reason not to use `invalid_extensions` instead?

Thank you again for this super handy extension!

**Comment by AdiY00** [comment]
Thanks!
I get what you're saying, but I feel like you could run into the same problem with `invalid_extensions`.

I'll see what I can do though.

**Comment by AdiY00** [comment]
Ended up adding `additional_extensions` and `exclude_extensions` to the config.
you can use them like this without having to list everything.
```lua
require("copy-tree").setup {
  additional_extensions = { "%.tf$", },
  exclude_extensions = { "%.coffee$", }
```

This way it also shouldn't break anything for anyone else.

Let me know what you think!
